

export const metadata = {
    title: "Analytics Page",
    description: "Generated by create next app",
  };

export default function Dashboard() {
    return (
        <div>
            <h1 className="text-5xl">Analytics</h1>
        </div>
    );
}