import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ul className="flex gap-4 mt-4">
         <li> <Link href="/">Home</Link></li> 
         <li> <Link href="/dashboard/analytics">Analytics</Link></li> 
         <li> <Link href="/dashboard/setting">Setting</Link></li> 
         <li> <Link href="/heavy">Heavy</Link></li> 
        </ul>
        <hr className="my-4 w-full h-1 bg-blue-200 border-0 dark:bg-red-700" />
        {children}
      </body>
    </html>
  );
}
