

export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="">
       <h1 className="text-3xl">Home Page</h1>
    </div>
  );
}
