

export const metadata = {
    title: "Setting Page",
    description: "Generated by create next app",
  };


export default function Dashboard() {
    return (
        <div>
            <h1 className="text-5xl">setting page</h1>
        </div>
    );
}